name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '30 4 * * *'

jobs:
  test:
    name: Run tests with ${{ matrix.shell }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell:
          - ash
          - bash
          - dash
          - zsh
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install ${{ matrix.shell }}
      - run: ${{ matrix.shell }} ./test/run.sh -s ${{ matrix.shell }}
